#!/bin/bash

host="$(cat /etc/hostname)"
# Get package installed
get_package_info() {
        pkg_count=$(get_pkg_count)


        if [ "$pkg_count" -ne 0 ]; then
                echo -n "$pkg_count"

                else
                echo "Unknown"
        fi
}
# Get uptime
# formatted uptime
get_up_time()
{
    uptime --pretty | sed 's/up //' | sed 's/\ years\?,/y/' | sed 's/\ weeks\?,/w/' | sed 's/\ days\?,/d/' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/'
}
# Get the init
get_init() {
        if [ "$kernel" = "Android" ]; then
vsfetch                                                                                     1,1            Top
